--- arch/arm/mach-msm/Makefile	2011-07-20 10:13:34.000000000 +0400
+++ arch/arm/mach-msm/Makefile	2011-07-31 16:40:28.000000000 +0400
@@ -61,9 +61,9 @@
 quiet_cmd_mkrpcsym = MKCAP   $@
 	cmd_mkrpcsym = $(PERL) $(srctree)/$(src)/mkrpcsym.pl $< $@
 
-target += smd_rpc_sym.c
-$(obj)/smd_rpc_sym.c: $(src)/smd_rpc_sym $(src)/mkrpcsym.pl
-	$(call if_changed,mkrpcsym)
+#target += smd_rpc_sym.c
+#$(obj)/smd_rpc_sym.c: $(src)/smd_rpc_sym $(src)/mkrpcsym.pl
+#	$(call if_changed,mkrpcsym)
 
 obj-y += modem_notifier.o
 obj-$(CONFIG_MSM_SMD_LOGGING) += smem_log-8x60.o
